#./start_extract_descriptor.sh 1 /nfs/nfs129/videos/short_video_pic 1  /devdata/videos/short_s1_h129.txt
#./start_extract_descriptor.sh 1 /nfs/nfs129/videos/short_video_pic 2  /devdata/videos/short_s2_h129.txt
#./start_extract_descriptor.sh 1 /nfs/nfs129/videos/short_video_pic 3  /devdata/videos/short_s3_h129.txt
#./start_extract_descriptor.sh 1 /nfs/nfs129/videos/short_video_pic 4  /devdata/videos/short_s4_h129.txt
#./start_extract_descriptor.sh 1 /nfs/nfs129/videos/short_video_pic 5  /devdata/videos/short_s5_h129.txt
#./start_extract_descriptor.sh 1 /nfs/nfs129/videos/short_video_pic 6  /devdata/videos/short_s6_h129.txt
#./start_extract_descriptor.sh 1 /nfs/nfs129/videos/short_video_pic 7  /devdata/videos/short_s7_h129.txt
#./start_extract_descriptor.sh 1 /nfs/nfs129/videos/short_video_pic 8  /devdata/videos/short_s8_h129.txt
#./start_extract_descriptor.sh 1 /nfs/nfs129/videos/short_video_pic 9  /devdata/videos/short_s9_h129.txt
